# Generated by Django 2.1.2 on 2018-10-15 21:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ors', '0002_auto_20181015_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginTrail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=60)),
                ('ip', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mobileNumber',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(regex='^\\d{4}([- ])\\d{7}|(\\+91[\\-\\s]?)?[0]?[0-9]\\d{9}$')]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='roll_no',
            field=models.CharField(default='000000', help_text='Unique identifier for the student', max_length=9, validators=[django.core.validators.RegexValidator(regex='^\\d{9}$')]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='year',
            field=models.CharField(choices=[('UG1', 'UG1'), ('UG2', 'UG2'), ('UG3', 'UG3'), ('UG4', 'UG4'), ('MS', 'MS'), ('Ph.D', 'Ph.D'), ('faculty', 'faculty'), ('none', 'none')], default='none', max_length=8),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=60),
        ),
        migrations.AddField(
            model_name='logintrail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ors.UserProfile'),
        ),
    ]
