# Generated by Django 2.1.2 on 2018-10-26 11:51

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import ors.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('electronics', 'electronics'), ('stationary', 'stationary'), ('fashion', 'fashion'), ('sports', 'sports'), ('lifestyle', 'lifestyle'), ('other', 'other')], max_length=20)),
                ('price', models.FloatField()),
                ('postdate', models.DateTimeField(auto_now_add=True)),
                ('duration', models.IntegerField(blank=True)),
                ('quantity', models.IntegerField(default=1)),
                ('ptype', models.CharField(choices=[('sell', 'sell'), ('rent', 'rent'), ('free', 'free')], default='free', max_length=4)),
                ('created_by', models.CharField(blank=True, max_length=60)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('modified_by', models.CharField(max_length=60, null=True)),
                ('modified_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='LoginTrail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=60)),
                ('ip', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('success', 'success'), ('failed', 'failed')], default='failed', max_length=10)),
                ('secure', models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', max_length=5)),
                ('server_name', models.CharField(default='unknown', max_length=30)),
                ('server_port', models.IntegerField(default=0)),
                ('device', models.CharField(default='unknown', max_length=42)),
                ('model', models.CharField(blank=True, max_length=42)),
                ('brand', models.CharField(blank=True, max_length=42)),
                ('browser', models.CharField(default='unknown', max_length=42)),
                ('os', models.CharField(default='unknown', max_length=42)),
            ],
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('dateStart', models.DateField()),
                ('dateEnd', models.DateField()),
                ('status', models.CharField(choices=[('requested', 'requested'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='requested', max_length=20)),
                ('created_by', models.CharField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ors.UserProfile'), max_length=60)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('modified_by', models.CharField(max_length=60, null=True)),
                ('modified_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=33)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('electronics', 'electronics'), ('stationary', 'stationary'), ('fashion', 'fashion'), ('sports', 'sports'), ('lifestyle', 'lifestyle'), ('other', 'other')], max_length=20)),
                ('price', models.FloatField(blank=True, null=True)),
                ('postdate', models.DateTimeField(auto_now_add=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('InStock', 'InStock'), ('OutofStock', 'OutofStock')], default='InStock', max_length=10)),
                ('image', models.FileField(default='default.jpg', upload_to=ors.models.product_directory_path)),
                ('ptype', models.CharField(choices=[('sell', 'sell'), ('rent', 'rent'), ('free', 'free')], default='free', max_length=4)),
                ('created_by', models.CharField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ors.UserProfile'), max_length=60)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('modified_by', models.CharField(max_length=60, null=True)),
                ('modified_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='ProductRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, default=1, max_digits=2)),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ors.UserProfile'), max_length=60)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('modified_by', models.CharField(max_length=60, null=True)),
                ('modified_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('complain', models.TextField()),
                ('created_by', models.CharField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ors.UserProfile'), max_length=60)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('modified_by', models.CharField(max_length=60, null=True)),
                ('modified_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='RequestSeller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('created_by', models.CharField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ors.UserProfile'), max_length=60)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('modified_by', models.CharField(max_length=60, null=True)),
                ('modified_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='SellerRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, default=1, max_digits=2)),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='ors.UserProfile'), max_length=60)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('modified_by', models.CharField(max_length=60, null=True)),
                ('modified_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=60, validators=[django.core.validators.RegexValidator(regex='^.+(iiits.in)$')])),
                ('mobileNumber', models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(regex='^\\d{4}([- ])\\d{7}|(\\+91[\\-\\s]?)?[0]?[0-9]\\d{9}$')])),
                ('roll_no', models.CharField(default='000000000', help_text='Unique identifier for the student', max_length=9, validators=[django.core.validators.RegexValidator(regex='^\\d{9}$')])),
                ('year', models.CharField(choices=[('UG1', 'UG1'), ('UG2', 'UG2'), ('UG3', 'UG3'), ('UG4', 'UG4'), ('MS', 'MS'), ('Ph.D', 'Ph.D'), ('faculty', 'faculty'), ('none', 'none')], default='none', max_length=8)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('bio', models.TextField(blank=True)),
                ('dp', models.FileField(blank=True, upload_to=ors.models.user_directory_path)),
                ('created_by', models.CharField(default=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL), max_length=60)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('modified_by', models.CharField(max_length=60, null=True)),
                ('modified_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('InStock', 'InStock'), ('OutofStock', 'OutofStock')], default='InStock', max_length=10)),
                ('quantity', models.IntegerField(default=1)),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('created_by', models.CharField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ors.UserProfile'), max_length=60)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('modified_by', models.CharField(max_length=60, null=True)),
                ('modified_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ors.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ors.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='sellerrating',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='ors.UserProfile'),
        ),
        migrations.AddField(
            model_name='sellerrating',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ors.UserProfile'),
        ),
        migrations.AddField(
            model_name='requestseller',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ors.UserProfile'),
        ),
        migrations.AddField(
            model_name='requestseller',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ors.Product'),
        ),
        migrations.AddField(
            model_name='requestseller',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='ors.UserProfile'),
        ),
        migrations.AddField(
            model_name='report',
            name='complainant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ors.UserProfile'),
        ),
        migrations.AddField(
            model_name='report',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ors.Product'),
        ),
        migrations.AddField(
            model_name='report',
            name='respondant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complainant', to='ors.UserProfile'),
        ),
        migrations.AddField(
            model_name='productrating',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ors.UserProfile'),
        ),
        migrations.AddField(
            model_name='productrating',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ors.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ors.UserProfile'),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ors.UserProfile'),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ors.Product'),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='ors.UserProfile'),
        ),
        migrations.AddField(
            model_name='archivedproduct',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ors.UserProfile'),
        ),
    ]
