# Generated by Django 2.1.2 on 2018-10-19 09:50

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('1', 'electronics'), ('2', 'stationary'), ('3', 'fashion'), ('4', 'sports'), ('5', 'lifestyle'), ('6', 'other')], max_length=20)),
                ('price', models.FloatField()),
                ('postdate', models.DateTimeField(auto_now_add=True)),
                ('duration', models.IntegerField(blank=True)),
                ('quantity', models.IntegerField(default=1)),
                ('ptype', models.CharField(choices=[('1', 'sell'), ('2', 'rent')], default='1', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_pic', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='LoginTrail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=60)),
                ('ip', models.CharField(max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('dateStart', models.DateField()),
                ('dateEnd', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=33)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('1', 'electronics'), ('2', 'stationary'), ('3', 'fashion'), ('4', 'sports'), ('5', 'lifestyle'), ('6', 'other')], max_length=20)),
                ('price', models.FloatField()),
                ('postdate', models.DateTimeField(auto_now_add=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('ptype', models.CharField(choices=[('sell', 'sell'), ('rent', 'rent'), ('free', 'free')], default='free', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='ProductRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, default=1, max_digits=2)),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('complain', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RequestSeller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='SellerRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, default=1, max_digits=2)),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=60, validators=[django.core.validators.RegexValidator(regex='^.+(iiits.in)$')])),
                ('mobileNumber', models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(regex='^\\d{4}([- ])\\d{7}|(\\+91[\\-\\s]?)?[0]?[0-9]\\d{9}$')])),
                ('roll_no', models.CharField(default='000000000', help_text='Unique identifier for the student', max_length=9, validators=[django.core.validators.RegexValidator(regex='^\\d{9}$')])),
                ('year', models.CharField(choices=[('UG1', 'UG1'), ('UG2', 'UG2'), ('UG3', 'UG3'), ('UG4', 'UG4'), ('MS', 'MS'), ('Ph.D', 'Ph.D'), ('faculty', 'faculty'), ('none', 'none')], default='none', max_length=8)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('dp', models.FileField(blank=True, upload_to='dp/')),
                ('user', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('InStock', 'InStock'), ('OutofStock', 'OutofStock')], default='InStock', max_length=10)),
                ('quantity', models.IntegerField(default=1)),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ors.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ors.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='sellerrating',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='ors.UserProfile'),
        ),
        migrations.AddField(
            model_name='sellerrating',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ors.UserProfile'),
        ),
        migrations.AddField(
            model_name='requestseller',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ors.UserProfile'),
        ),
        migrations.AddField(
            model_name='requestseller',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ors.Product'),
        ),
        migrations.AddField(
            model_name='requestseller',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='ors.UserProfile'),
        ),
        migrations.AddField(
            model_name='report',
            name='complainant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ors.UserProfile'),
        ),
        migrations.AddField(
            model_name='report',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ors.Product'),
        ),
        migrations.AddField(
            model_name='report',
            name='respondant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complainant', to='ors.UserProfile'),
        ),
        migrations.AddField(
            model_name='productrating',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ors.UserProfile'),
        ),
        migrations.AddField(
            model_name='productrating',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ors.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ors.UserProfile'),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ors.Product'),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ors.UserProfile'),
        ),
        migrations.AddField(
            model_name='archivedproduct',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ors.UserProfile'),
        ),
    ]
