# Generated by Django 2.1.2 on 2018-10-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logintrail',
            name='user',
        ),
        migrations.AddField(
            model_name='logintrail',
            name='host_name',
            field=models.CharField(default='unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='logintrail',
            name='status',
            field=models.CharField(choices=[('success', 'success'), ('failed', 'failed')], default='failed', max_length=10),
        ),
    ]
