# Generated by Django 2.1.2 on 2018-10-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ors', '0002_auto_20181025_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='status',
            field=models.CharField(choices=[('requested', 'requested'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='requested', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('InStock', 'InStock'), ('OutofStock', 'OutofStock')], default='InStock', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='archivedproduct',
            name='category',
            field=models.CharField(choices=[('electronics', 'electronics'), ('stationary', 'stationary'), ('fashion', 'fashion'), ('sports', 'sports'), ('lifestyle', 'lifestyle'), ('other', 'other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='archivedproduct',
            name='ptype',
            field=models.CharField(choices=[('sell', 'sell'), ('rent', 'rent'), ('free', 'free')], default='free', max_length=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
