# Generated by Django 2.1.2 on 2018-10-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ors', '0002_auto_20181021_0229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logintrail',
            old_name='host_name',
            new_name='remote_host',
        ),
        migrations.AddField(
            model_name='logintrail',
            name='secure',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', max_length=5),
        ),
        migrations.AddField(
            model_name='logintrail',
            name='server_name',
            field=models.CharField(default='unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='logintrail',
            name='server_port',
            field=models.IntegerField(default=0, max_length=30),
        ),
    ]
