# Generated by Django 2.1.2 on 2018-10-25 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ors', '0003_auto_20181026_0116'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExampleModel',
        ),
    ]
