# Generated by Django 2.1.2 on 2018-10-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ors', '0003_auto_20181021_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logintrail',
            name='server_port',
            field=models.IntegerField(default=0),
        ),
    ]
