# Generated by Django 2.1.2 on 2018-10-20 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ors', '0004_auto_20181021_0309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logintrail',
            name='remote_host',
        ),
    ]
