# Generated by Django 2.1.2 on 2018-11-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ors', '0005_auto_20181102_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='dateEnd',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='dateStart',
            field=models.DateField(blank=True, null=True),
        ),
    ]
