# Generated by Django 2.1.2 on 2018-10-20 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ors', '0005_remove_logintrail_remote_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='logintrail',
            name='brand',
            field=models.CharField(blank=True, max_length=42),
        ),
        migrations.AddField(
            model_name='logintrail',
            name='browser',
            field=models.CharField(default='unknown', max_length=42),
        ),
        migrations.AddField(
            model_name='logintrail',
            name='device',
            field=models.CharField(default='unknown', max_length=42),
        ),
        migrations.AddField(
            model_name='logintrail',
            name='model',
            field=models.CharField(blank=True, max_length=42),
        ),
        migrations.AddField(
            model_name='logintrail',
            name='os',
            field=models.CharField(default='unknown', max_length=42),
        ),
    ]
