# Generated by Django 2.1.2 on 2018-11-06 08:45

from django.db import migrations, models
import django.db.models.deletion
import ors.models


class Migration(migrations.Migration):

    dependencies = [
        ('ors', '0006_auto_20181102_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='productImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(default='default.jpg', upload_to=ors.models.product_directory_path)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ors.UserProfile')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ors.Product')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_id', to='ors.Product')),
            ],
        ),
    ]
