# Generated by Django 2.1.2 on 2018-10-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ors', '0006_auto_20181021_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.FileField(default='default.jpg', upload_to='product/'),
        ),
    ]
