# Generated by Django 2.1.2 on 2018-11-06 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ors', '0007_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='product_name',
            new_name='name',
        ),
    ]
