# Generated by Django 2.1.2 on 2018-10-22 15:28

from django.db import migrations, models
import ors.models


class Migration(migrations.Migration):

    dependencies = [
        ('ors', '0007_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(default='default.jpg', upload_to=ors.models.product_directory_path),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dp',
            field=models.FileField(blank=True, upload_to=ors.models.user_directory_path),
        ),
    ]
