# Generated by Django 2.1.2 on 2018-11-06 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ors', '0008_auto_20181106_1419'),
        ('ors', '0007_auto_20181106_0741'),
    ]

    operations = [
    ]
