# Generated by Django 2.1.2 on 2018-11-06 18:28

from django.db import migrations, models
import ors.models


class Migration(migrations.Migration):

    dependencies = [
        ('ors', '0010_auto_20181106_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='status',
            field=models.CharField(choices=[('requested', 'requested'), ('accepted', 'accepted'), ('rejected', 'rejected'), ('confirmed', 'confirmed')], default='requested', max_length=20),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.FileField(default='default.jpg', upload_to=ors.models.image_directory_path),
        ),
    ]
