# Generated by Django 2.1.2 on 2018-11-09 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ors', '0011_auto_20181106_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='notification',
            name='typ',
            field=models.CharField(default='request', max_length=36),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='boughtDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='requestseller',
            name='status',
            field=models.CharField(choices=[('requested', 'requested'), ('accepted', 'accepted'), ('rejected', 'rejected'), ('confirmed', 'confirmed')], default='requested', max_length=20),
        ),
    ]
