# Generated by Django 2.1.2 on 2018-11-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ors', '0012_auto_20181109_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='requestseller',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
