# Generated by Django 2.1.2 on 2018-11-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ors', '0013_auto_20181109_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='duration',
        ),
        migrations.AddField(
            model_name='product',
            name='period',
            field=models.CharField(choices=[('per Day', 'per Day'), ('per Week', 'per Week'), ('per Month', 'per Month')], default='per Day', max_length=60),
        ),
    ]
