# Generated by Django 2.1.2 on 2018-11-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ors', '0017_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='period',
            field=models.CharField(blank=True, choices=[('per Day', 'per Day'), ('per Week', 'per Week'), ('per Month', 'per Month'), ('None', 'None')], default='None', max_length=60, null=True),
        ),
    ]
